development:
  adapter: postgresql
  host: grade-pending.coe8ua7gofeg.us-west-2.rds.amazonaws.com
  username: grade_pending
  password: gotanABorC
  port: 5432
  database: gp1
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  host: grade-pending.coe8ua7gofeg.us-west-2.rds.amazonaws.com
  username: grade_pending
  password: gotanABorC
  port: 5432
  database: gptest
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gradePending_production
  pool: 5
  timeout: 5000
