development:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gradePending_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gradePending_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gradePending_production
  pool: 5
  timeout: 5000
