development:
  adapter: postgresql
  host: gpdb2.coe8ua7gofeg.us-west-2.rds.amazonaws.com  
  username: grade_pending
  password: hiJackThis
  port: 5432
  database: gp1
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  host: gpdb2.coe8ua7gofeg.us-west-2.rds.amazonaws.com   
  username: grade_pending
  password: hiJackThis
  port: 5432
  database: gp1
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  host: localhost
  username:
  password:
  database: gradePending_production
  pool: 5
  timeout: 5000
